### PR TITLE
add events polyfill as explicit dependency for browsers & webpack 5 compatibility

### PR DESCRIPTION
**Pull request by gfortaine**

### CODE REVIEW

**Comment by OlliV** [comment]
@timneutkens what do you think? I would add you as a reviewer but you are not in the group set for this repo.

**Comment by timneutkens** [comment]
If it's going to be used in browsers it should be using `mitt` instead of the Node.js eventemitter. However this package wasn't meant to be used in browsers when it was created.

**Comment by OlliV** [comment]
Yeah, that's correct, it was never my intention. However, many do use it in browser.

**Comment by gfortaine** [comment]
Given that this package wasn’t intended to be used in browsers, it looks like that we would do better to move forward with an alternative solution like this one [@shopify/semaphore](https://www.npmjs.com/package/@shopify/semaphore)

**Comment by OlliV** [comment]
By a quick look, that looks probably better for your use case.

**Pull request closed without merging**
