### PR TITLE
Fix edge runtime compatibility

### LINKED ISSUE #48: Uncaught TypeError: Class extends value #<Object> is not a constructor or null
Whenever I import Sema or RateLimit.

i.e `import { RateLimit, Sema } from 'async-sema';`

I'm getting the following error:

`Uncaught TypeError: Class extends value #<Object> is not a constructor or null`

Is there any workaround for it?

Thanks.

### LINKED ISSUE #56017: `async-sema` not working in edge runtime: ` Class extends value [object Object] is not a constructor or null`
### Link to the code that reproduces this issue

https://github.com/remorses/next-bug-import-events

### To Reproduce

1. next dev
2. visit browser
3. see server error ` Class extends value [object Object] is not a constructor or null`

### Current vs. Expected behavior

`async-sema` should work in edge runtime

### Verify canary release

- [X] I verified that the issue exists in the latest Next.js canary release

### Provide environment information

```bash
Operating System:
  Platform: darwin
  Arch: arm64
  Version: Darwin Kernel Version 22.6.0: Wed Jul  5 22:21:53 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6020
Binaries:
  Node: 18.16.1
  npm: 9.5.1
  Yarn: 1.22.19
  pnpm: 8.7.6
Relevant Packages:
  next: 13.5.4-canary.0
  eslint-config-next: 13.5.1
  react: 18.2.0
  react-dom: 18.2.0
  typescript: 5.2.2
Next.js Config:
  output: N/A
```

### Which area(s) are affected? (Select all that apply)

Middleware / Edge (API routes, runtime)

### Additional context

This issue is caused by `async-sema` importing `EventEmitter` with default import: `import EventEmitter from 'events'`, this was previously working but not anymore, the default import is now an object with all exports as fields

https://github.com/vercel/async-sema/blob/603842b82e68e24b76eb0e74dae66de1eda468b4/src/index.ts#L1

### PR DESCRIPTION
**Pull request by remorses**
Fix #48 
Fix https://github.com/vercel/next.js/issues/56017

### CODE REVIEW

**Comment by jdalrymple** [comment]
Any ETA on this PR?

**Comment by remorses** [comment]
@leerob can you take a look?

**Comment by jdalrymple** [comment]
@remorses  I got impatient and did a clean up and update here: https://github.com/jdalrymple/sema4. Adding more tests now to have complete coverage.

**Comment by remorses** [comment]
@jdalrymple  cool name

**Pull request closed without merging**
